### ISSUE TITLE
mate-volume-control-applet hidpi icon

### ISSUE THREAD

**Issue by Safari77** [mate-desktop/mate-media#114] opened 2018-07-21 09:34 UTC
#### Expected behaviour
non-blurry icon shown in mate-panel

#### Actual behaviour
blurry icon
![mate-vol](https://user-images.githubusercontent.com/3876865/43034279-0244fdba-8cda-11e8-86c4-840b4eec3031.png)

#### MATE general version
1.21

#### Package version
1.21.0

**Comment by raveit65** [comment] 2018-07-21 10:13
Confirmed.
Thank you for reporting this issue.
Why you have 2 grip areas in your screenshots (the 3 points)?
This looks wrong.
And ` Link to downstream report of your Distribution ` has a different meaning :)
This area is for a link to a downstream report for your distro (redhat bugzilla).
We add this area to get downstream maintainers involved and given him a chance to confirming if it isn't a distro issue.
The right place for adding an image is `Actual behaviour`
Any way, in this case you posted the downstream report to the same person which would read the downstream report, me :)

**Comment by Safari77** [comment] 2018-07-22 12:44
I added a separator manually, that's why it looks like that.
BUT I accidentally removed the nm-applet icon and volume control instead of the separator, and I could not get those two icons back without restoring mate panel settings (```Add to Panel```doesn't list them).

Also moved the image to correct section...

**Comment by raveit65** [comment] 2018-07-22 12:53
> and I could not get those two icons back without restoring mate panel settings (Add to Panel doesn't list them).

Because they aren't panel applets, they are only applets for the notification-area which are visible if the application is running.
In other words you need to restart them again from command line or restart session, because they are in autostart.
`mate-volume-control-applet`
`nm-applet`

**Comment by raveit65** [comment] 2018-12-22 12:38
@vkareh 
Do you think it is possible to scale the icon for HIDIPI support?
Same for mate-display-applet.
I know you're using ubuntu indicator applets in ubuntu and you don't see the blurred icons.
But there are distros which don't have this alternative.

**Comment by vkareh** [comment] 2018-12-22 13:32
@raveit65 - actually my work computer now runs Fedora 29, but the screen is not HiDPI (the card should support it, I just need an external HiDPI monitor). Also, I've added the tray to my Ubuntu laptop and I can definitely see the blurry icon.

I can work on this tomorrow morning.

**Comment by vkareh** [comment] 2018-12-23 13:07
hmmm... yeah this uses GtkStatusIcon... the only way that I can resize this is by hacking the na-tray applet in the mate-panel, or by forking GtkStatusIcon and updating it with HiDPI magic... I'll try the mate-panel approach, but sooner or later we will have to fork and port GtkStatusIcon and maintain it ourselves

**Comment by raveit65** [comment] 2018-12-23 13:59
Yes, that is problem. I tried to add a style_contex css class to the volume applet today, which failed because GtkStatusIcon isn't a widget :/
I hope you will find a solution for na-tray applet.

Another solution for future might be to convert the volume-applet to a normal applet.
In older mate-media releases < 1.10 we had a gst-mixer-applet which was a normal panel applet.
This was dropped because gst-mixer was gone with gstreamer-1.0.
I don't get it why it is needed that volume-applet is a tray applet, because it is always there.

**Comment by lukefromdc** [comment] 2018-12-23 21:01
In forking GtkStatusIcon, the issue would become all the non-MATE applications that use status icons, though a tray supporting both protocols might not be too hard to make. I'm pretty sure GtkStatusIcon used Xembed directly, and there would even be the opportunity to write a wayland-compatable codepath to get the desired icon position (x and y coordinates from the tray) and render it there in a wayland window.  

I would call that "MateStatusIcon" and in X11 would want to see it work wherever GtkStatusIcon is supported by the tray, meaning an application calling MateStatusIcon uses the Freedesktop tray protocol exactly the same as before in X11. 

What WOULD work now is a port to indicator/SNI, though the disadvantage there is that sliders in indicators must be horizontal, as only menu items can be loaded into an indicator popup because it is always a menu.

**Comment by monsta** [comment] 2019-02-09 16:22
Even though GtkStatusIcon is deprecated, they still accept fixes for it. Remember corrupted/duplicate icons reported in https://github.com/mate-desktop/mate-panel/issues/666#issuecomment-428832727 and https://github.com/mate-desktop/mate-panel/issues/793? It had been fixed by @muktupavels in https://github.com/GNOME/gtk/commit/31d896c5cf5449fb1c24c7180cf3eea62c2f506e. If you have GTK+ 3.24.3, it has the fix.

Also... are you sure it's GtkStatusIcon that makes our icon blurry? It might be in the app itself... XEmbed just displays whatever the app sends...

Are there other apps that have similar blurry tray icon?

**Comment by vkareh** [comment] 2019-02-09 17:21
Pretty much all GtkStatusIcons look blurry, unless they don't scale with size, in which case they look sharp only because they are smaller than the tray applet requests.

GtkStatusIcons does not take into account scale_factor or using surfaces for rendering. They might look fine on scale=1, but as soon as you go up it is blurry.

I started working on some possible fixes for GtkStatusIcons locally and see what happens... I've never done GTK development, so we'll see :P

**Comment by lukefromdc** [comment] 2019-02-09 19:04
At any rate, a wayland compatable mate-panel will need a sound applet (in progress) or a sound indicator (Ubuntu's won't even build on Debian it's so complex). The existing volume control applet work, followed by a port of all the applets to in-process would give us a a wayland-compatable volume control applet.

**Comment by monsta** [comment] 2019-02-10 17:59
Ok, so it affects nm-applet too? (probably the most used GtkStatusIcon out there :slightly_smiling_face:)

**Comment by vkareh** [comment] 2019-02-10 18:11
@monsta - yes, it looks awful on HiDPI, unfortunately

**Comment by raveit65** [comment] 2019-02-11 08:19
@monsta 
Current nm-applet 
![bildschirmfoto zu 2019-02-08 11-36-50](https://user-images.githubusercontent.com/961604/52551457-e9330200-2ddc-11e9-948f-33a7f9d1dd59.png)
Blueberry and dropbox applet are blurred too.
Maybe Dropbox needs only to push their qt version. Qt 5.6 started with supporting HIDPI.

**Comment by lukefromdc** [comment] 2019-02-11 08:33
https://github.com/mate-desktop/mate-media/pull/118 which ports mate-media to a panel applet (not a GtkStatusIcon) now has a proper and responsive mute menu, seems to be at feature parity with our normal mate-media tray icon. I have three long days of work in that but finally got the mute menu working

**Comment by monsta** [comment] 2019-02-17 09:12
@vkareh: this code in [gtkstatusicon.c](https://github.com/GNOME/gtk/blob/gtk-3-24/gtk/deprecated/gtkstatusicon.c#L1415) might be relevant...

```C
  icon_helper = gtk_icon_helper_new (gtk_style_context_get_node (gtk_widget_get_style_context (widget)), widget);
  _gtk_icon_helper_set_force_scale_pixbuf (icon_helper, TRUE);
  _gtk_icon_helper_set_definition (icon_helper, priv->image_def);
  _gtk_icon_helper_set_icon_size (icon_helper, GTK_ICON_SIZE_SMALL_TOOLBAR);
  _gtk_icon_helper_set_pixel_size (icon_helper, round_size);
  surface = gtk_icon_helper_load_surface (icon_helper, 1);
  if (surface)
    {
      pixbuf = gdk_pixbuf_get_from_surface (surface, 0, 0,
                                            cairo_image_surface_get_width (surface),
                                            cairo_image_surface_get_height (surface));
      cairo_surface_destroy (surface);
}
```

These "icon helper" functions are in [gtkiconhelper.c](https://github.com/GNOME/gtk/blob/gtk-3-24/gtk/gtkiconhelper.c). The second argument of `gtk_icon_helper_load_surface` is `scale` which is hardcoded to 1 in the above code fragment...

**Comment by vkareh** [comment] 2019-05-07 13:32
Fixed by https://github.com/mate-desktop/mate-media/pull/118

**Closed by vkareh** 2019-05-07 13:32 UTC
Labels: confirmed
